# Generated by Django 3.1.6 on 2021-02-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=264, unique=True)),
                ('nick', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
