# Generated by Django 3.1.6 on 2021-02-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRedSocial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nick',
            field=models.CharField(default=1, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
