# Generated by Django 3.1.6 on 2021-02-18 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRedSocial', '0006_auto_20210218_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nick',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^1', 'nick')]),
        ),
    ]
