# Generated by Django 3.1.6 on 2021-02-18 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRedSocial', '0007_auto_20210218_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nick',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('[1]', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')]),
        ),
    ]
