# Generated by Django 3.1.6 on 2021-02-24 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppRedSocial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('apellido', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=264, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('nick', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='AppRedSocial.user')),
            ],
        ),
    ]
