# Generated by Django 3.1.6 on 2021-02-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('apellido', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=264, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('nick', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
