# Generated by Django 3.1.6 on 2021-02-25 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('publicacion', '0002_auto_20210225_1515'),
        ('cabecera', '0002_auto_20210225_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabecera',
            name='historia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publicacion.historia'),
        ),
        migrations.AlterField(
            model_name='cabecera',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
