# Generated by Django 3.1.6 on 2021-02-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRedSocial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_user',
            field=models.IntegerField(default=1, max_length=100, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='nick',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
